### PR TITLE
feat: live preview for baseline correction

### PR DESCRIPTION
**Pull request by hamed-musallam**
#1620

### CODE REVIEW

**Comment by lpatiny** [comment]
I tried with polynomial correction and each time I add a zone I expect to see new spectrum but it does not work.

**Comment by hamed-musallam** [comment]
@lpatiny this is another story, I made the live update just when change the options in the header. I will implement it also when you add zones

**Comment by lpatiny** [comment]
Functionality is ok now. But why when we click on baseline correction we have vertical rescale. Quite annoying this and I would prefer it does not happen.

**Comment by hamed-musallam** [comment]
@lpatiny 

can you test it again?

**Comment by hamed-musallam** [comment]
@lpatiny 

can you test this PR again and check also the phase correction

**Comment by lpatiny** [comment]
Why was this PR closed ?

There is still a little problem of zoom out in case you don't apply the changes.

**Comment by hamed-musallam** [comment]
@lpatiny 

It is closed by mistake.

**Comment by hamed-musallam** [comment]
@lpatiny 
Do you mean when we press cancel? is this in all the filters or just in the baseline correction?

**Pull request merged**
