### PR TITLE
feat: sort spectra by specific parameter

### PR DESCRIPTION
**Pull request by hamed-musallam**
The spectra are sorting without mutating the original state

- https://github.com/cheminfo/nmrium/issues/3232
- https://github.com/cheminfo/nmrium/issues/3233

### CODE REVIEW

**Comment by lpatiny** [comment]
Exporting the raw data is working perfectly.

Concerning sorting, is there any reason I can not sort by an integration value ?

image

**Comment by hamed-musallam** [comment]
> Exporting the raw data is working perfectly.
> 
> Concerning sorting, is there any reason I can not sort by an integration value ?
> 
> image

The way we sort the integration is different from how we sort the spectrum parameter.

**Comment by lpatiny** [comment]
Would it be possible to toggle between 3 states ? Sort up / Sort down / reset to original order.

Also would it be difficult to also add the sort by integral ?

**Review by lpatiny — APPROVED** [review]
Functionality LGTM

**Pull request merged**
