### PR TITLE
feat:  panel preferences

### PR DESCRIPTION
**Pull request by hamed-musallam**
Refactor panels preferences based on #1524 , #1545 and integral width and colour preferences by nucleus 
image

### CODE REVIEW

**Comment by hamed-musallam** [comment]
@lpatiny 

can you check the functionality?

**Comment by lpatiny** [comment]
There is no way to format the coupling constant in Hz in the range panel, the option is missing

image

**Comment by lpatiny** [comment]
Please rename 

Nuclei formatting -> Number formatting for crosshair and info line.

image

**Comment by lpatiny** [comment]
In Ranges, please format the 'delta (Hz)' even for a range using the 'Hz' formatting.

image

Please rename in the preferences or ranges:

image

From -> From (ppm)
To -> To (ppm)
Absolute -> Absolute integration
Relative -> relative integraton

**Comment by lpatiny** [comment]
In zones seems the preferences change nothing at all.

image

In does not make sense to have Absolute and Relative for each nucleus. The integration is expected to be the integration under the full drawn zone.

So in the preferences of zones we should have:
- For each nucleus, 1H, 13C, etc the preferences for '∂ (ppm)' (just formatting, no way to hide)
- Globally (not for each nucleus): 'Absolute integration', 'Relative integration'

The possibility to display the columns to display the integrations.

**Comment by hamed-musallam** [comment]
@lpatiny 

how to calculate the integration of the relative and the absolute value for zones?

**Comment by lpatiny** [comment]
> @lpatiny
> 
> how to calculate the integration of the relative and the absolute value for zones?

For now just remove everything related to integral on Zone. We don't calculate it for now.

**Pull request merged**
