### PR TITLE
feat: add the 'source' property for original file

### PR DESCRIPTION
**Pull request by jobo322**
fix: fix parse ACS string (resurrect)
closes: https://github.com/cheminfo/nmrium/issues/1251

feat: add nmr-load-save source
closes: https://github.com/cheminfo/nmrium/issues/2148

close: #2146

### CODE REVIEW

**Comment by lpatiny** [comment]
Please take care that the integration zone (from / to) spans over the full peak:

image

**Comment by jobo322** [comment]
> Please take care that the integration zone (from / to) spans over the full peak:
> 
> image

it looks much better

image

**Comment by hamed-musallam** [comment]
@targos 

it seems to me it is a bug in Firefox, WDT ? 

image

**Comment by targos** [comment]
I don't know, can you reproduce locally?

**Comment by hamed-musallam** [comment]
> I don't know, can you reproduce locally?

Yes, I got the same error when running the test locally

**Pull request merged**
