### PR TITLE
1h spectrum molecules test

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/cheminfo/nmrium/issues/1703

### CODE REVIEW

**Comment by lpatiny** [comment]
Please take care that we would like to Copy as molfile (and not save). 

After copy as molfile you may as well paste the molecule to check if there is really a new molecule inserted.

**Comment by lpatiny** [comment]
When we add those structures in the 'structure' panel they should also appear in the dialog box in integrals and ranges. Please check that this is the case.

**Comment by wadjih-bencheikh18** [comment]
> After copy as molfile you may as well paste the molecule to check if there is really a new molecule inserted.

Would i give chromium clipboard read access?

**Comment by lpatiny** [comment]
> Would i give chromium clipboard read access?

If needed yes but this time is copy as text and maybe the rights are different.

**Pull request merged**
