### PR TITLE
feat: 2D phase correction

### PR DESCRIPTION
**Pull request by hamed-musallam**
- [x] select pivot based on the sum (same code as add missing projections)
- [x] IF phase2D is selected, scroll wheel scale the 1D spectra (the traces)
- [x] IF phase2D is selected, SHIFT + scroll wheel scale the 2D (optional)
- [x] If over a trace, backspace will delete the trace (highlight of a zone of 10 pixels)
- [x] Selecting the pivot using SHIFT + click
- [x] The traces should share the same vertical domain
- [x] For 1D phase correction change the behaviour so that pivot is SHIFT + click
- [x] For vertical phase correction the spectra has to be vertical.
- [x] apply phase correction over the traces.

### CODE REVIEW

**Comment by lpatiny** [comment]
- select pivot based on the sum (same code as add missing projections)
- IF phase2D is selected, scroll wheel scale the 1D spectra (the traces)
- IF phase2D is selected, SHIFT + scroll wheel scale the 2D (optional)
- If over a trace, backspace will delete the trace (highlight of a zone of 10 pixels)
- Selecting the pivot using SHIFT + click
- For 1D phase correction change the behaviour so that pivot is SHIFT + click
- For vertical phase correction the spectra has to be vertical.

**Comment by hamed-musallam** [comment]
we have an issue with the ml-matrix package

for example in openChemLib package and the same for other packages that use ml-matrix
`
getConnectivityMatrix.js:73 Uncaught (in promise) TypeError: Matrix is not a constructor
    at getConnectivityMatrix (getConnectivityMatrix.js:73:32)
    at Re$1 (nmr-processing.mjs:2:7479)
    at G0 (nmr-processing.mjs:2:12569)
    at useAutoAssignments.ts:60:28
`

**Comment by targos** [comment]
How can I reproduce?

**Comment by hamed-musallam** [comment]
You could build the project on your local machine and experiment with features such as automatic assignment. Likewise, you can observe the same behavior when examining other unsuccessful test cases

https://github.com/cheminfo/nmrium/assets/35760236/f85c6a92-b835-400b-bffb-835504acc345

**Comment by lpatiny** [comment]
Are you sure you have all the new dependencies ?
I did `rm -rf package-lock.json node_modules` and `npm i` and could not reproduce this issue.

**Comment by hamed-musallam** [comment]
> Are you sure you have all the new dependencies ? I did `rm -rf package-lock.json node_modules` and `npm i` and could not reproduce this issue.

yes, I did try to remove the node_modules and packge-lock.json and i still get the same error.

**Comment by targos** [comment]
Like Luc, I cannot reproduce. I did the same things as your video but it works.

**Comment by hamed-musallam** [comment]
did you build the project locally on your machine `npm run build-no-minify` and try to run the playwright tests or use a local runner like https://www.npmjs.com/package/serve `serve build`

**Comment by targos** [comment]
I did not, sorry.

**Comment by targos** [comment]
Ok so I fixed what I hope is the last esm-related bug

**Pull request merged**
