### PR TITLE
fix loading troubles

### PR DESCRIPTION
**Pull request by jobo322**

### CODE REVIEW

**Comment by hamed-musallam** [comment]
We still have some issues

1- the carbon axis domain is wrong 
https://s3.uni-jena.de/nmrxiv/production/archive/5a1698da-4270-4114-b588-f258b9fd44d3/Apigenin%20annotated%20NMR%20400MHz%20DMSOd6%20data.zip

Screenshot 2023-11-20 at 09 33 37
Screenshot 2023-11-20 at 09 30 37

2- Problem with determination of gyromagnetic ratio

https://s3.uni-jena.de/nmrxiv/production/archive/2cd25088-4513-40ad-8aa6-21ff1f4e3527/%20Lupeol%20900MHz%20400MHz%20CDCl3%20NMR%20data%20.zip


Screenshot 2023-11-20 at 09 28 17

**Comment by hamed-musallam** [comment]
@lpatiny 
Should we open the logger window for the warning messages?
Screenshot 2023-11-20 at 09 36 38

**Comment by lpatiny** [comment]
> @lpatiny Should we open the logger window for the warning messages? Screenshot 2023-11-20 at 09 36 38

I would keep only for error for now.

**Comment by hamed-musallam** [comment]
@jobo322 

we found another issue in the jcamp parser 

https://s3.uni-jena.de/nmrxiv/production/archive/a9d8c2a7-fc95-4eb6-84dd-107548aa0c48/12c_HEE296.zip
image

**Pull request merged**
