### PR TITLE
refactor PredictSpectraModal using react-science

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
Refs: https://github.com/cheminfo/nmrium/issues/1537

### CODE REVIEW

**Review by targos — CHANGES_REQUESTED** [review]
The modal should be closed when you click the predict button

**Comment by wadjih-bencheikh18** [comment]
We still have one problem which is that the loading dialog must be above the modal, I tried to change `zIndex` but it doesn't fix it

**Comment by targos** [comment]
To me, the problem is that we should not use a separate loading alert if the modal stays open. Instead, we should either:
- Keep the loading alert, but close the modal immediately 
- Remove the loading alert and display something inside the modal

**Comment by targos** [comment]
There's something wrong with your Prettier

**Comment by wadjih-bencheikh18** [comment]
> There's something wrong with your Prettier

fixed. I had a problem in my vscode settings

**Review by targos — APPROVED** [review]

**Pull request merged**
