### PR TITLE
Refactor: NMRium preferences

### PR DESCRIPTION
**Pull request by hamed-musallam**
- remove "hide"  from all keys names inside the panels and tools and panels keys accept 3 values (true, false, and hide) instead of 2 values in the past (true and false), 

- NMRium will use the default workspace unless you specify the workspace.

- NMRium will reset the workspace data to default one if you try to hack and change the local storage to show panels you are not allowed to show it.

- Add new workspace for Prediction

### CODE REVIEW

**Comment by lpatiny** [comment]
Exercises currently displays all the panels and this does not seem normal

image

**Comment by lpatiny** [comment]
@hamed-musallam Is this still a work in progress ? There is the problem with the exercises that display all the panels.

**Comment by hamed-musallam** [comment]
@lpatiny 

yes it still in progress, i will finished it today

**Comment by lpatiny** [comment]
In the example like ethylvinylether I don't expect that workspace is being specified in the component and nevertheless it does not reload my last selected workspace.

Is this normal ?

Otherwise it looks of to me.

**Comment by lpatiny** [comment]
I think there is a bug in updating preferences. If preferences exists (in my case v4) you can save preferences or reload the page they will never change

Here are my preferences in localstorage:
```json 
{"version":4,"workspaces":{"default":{"version":1,"label":"Default workspace","display":{"general":{"disableMultipletAnalysis":false,"hideSetSumFromMolecule":false,"hideGeneralSettings":false,"experimentalFeatures":{"display":true}},"panels":{"spectraPanel":{"display":true,"open":true},"informationPanel":{"display":true,"open":false},"peaksPanel":{"display":true,"open":false},"integralsPanel":{"display":true,"open":false},"rangesPanel":{"display":true,"open":false},"structuresPanel":{"display":true,"open":false},"filtersPanel":{"display":true,"open":false},"zonesPanel":{"display":true,"open":false},"summaryPanel":{"display":false,"open":false},"multipleSpectraAnalysisPanel":{"display":false,"open":false},"databasePanel":{"display":false,"open":false},"predictionPanel":{"display":false,"open":false}}},"controllers":{"dimmedSpectraTransparency":0.1},"formatting":{"nucleus":[{"key":"1H","name":"1H","ppm":"0.00","hz":"0.00"},{"key":"13C","name":"13C","ppm":"0.00","hz":"0.00"},{"key":"15N","name":"15N","ppm":"0.00","hz":"0.00"},{"key":"19F","name":"19F","ppm":"0.00","hz":"0.00"},{"key":"29Si","name":"29Si","ppm":"0.00","hz":"0.00"},{"key":"31P","name":"31P","ppm":"0.00","hz":"0.00"}],"nucleusByKey":{},"panels":{}}},"process1D":{"version":1,"label":"Process 1D workspace","display":{"general":{"disableMultipletAnalysis":true},"panels":{"zonesPanel":true,"summaryPanel":true,"multipleSpectraAnalysisPanel":true},"toolBarButtons":{"import":false,"exportAs":false,"autoRangesTool":false,"multipleSpectraAnalysisTool":false,"exclusionZonesTool":false}},"controllers":{"dimmedSpectraTransparency":0.1},"formatting":{"nucleus":[{"key":"1H","name":"1H","ppm":"0.00","hz":"0.00"},{"key":"13C","name":"13C","ppm":"0.00","hz":"0.00"},{"key":"15N","name":"15N","ppm":"0.00","hz":"0.00"},{"key":"19F","name":"19F","ppm":"0.00","hz":"0.00"},{"key":"29Si","name":"29Si","ppm":"0.00","hz":"0.00"},{"key":"31P","name":"31P","ppm":"0.00","hz":"0.00"}],"nucleusByKey":{},"panels":{}}},"exercise":{"version":1,"label":"Exercise workspace","display":{"general":{"disableMultipletAnalysis":true,"hideSetSumFromMolecule":true,"hideGeneralSettings":true},"panels":{"spectraPanel":true,"integralsPanel":true},"toolBarButtons":{"zoomTool":true,"zoomOutTool":true,"import":false,"exportAs":false,"spectraStackAlignments":true,"spectraCenterAlignments":true,"realImaginary":false,"peakTool":true,"integralTool":true,"zonePickingTool":false,"slicingTool":false,"autoRangesTool":false,"zeroFillingTool":false,"phaseCorrectionTool":false,"baseLineCorrectionTool":false,"FFTTool":false,"multipleSpectraAnalysisTool":false,"exclusionZonesTool":false}},"controllers":{"dimmedSpectraTransparency":0.1},"formatting":{"nucleus":[{"key":"1H","name":"1H","ppm":"0.00","hz":"0.00"},{"key":"13C","name":"13C","ppm":"0.00","hz":"0.00"},{"key":"15N","name":"15N","ppm":"0.00","hz":"0.00"},{"key":"19F","name":"19F","ppm":"0.00","hz":"0.00"},{"key":"29Si","name":"29Si","ppm":"0.00","hz":"0.00"},{"key":"31P","name":"31P","ppm":"0.00","hz":"0.00"}],"nucleusByKey":{},"panels":{}}},"I05KIwbm":{"version":1,"label":"abc","display":{"general":{"disableMultipletAnalysis":true,"hideSetSumFromMolecule":true,"hideGeneralSettings":true},"panels":{"spectraPanel":true,"informationPanel":"hide","peaksPanel":"hide","integralsPanel":true,"rangesPanel":"hide","structuresPanel":"hide","filtersPanel":"hide","zonesPanel":"hide","summaryPanel":"hide","multipleSpectraAnalysisPanel":"hide","databasePanel":"hide","predictionPanel":"hide"},"toolBarButtons":{"zoomTool":true,"zoomOutTool":true,"import":false,"exportAs":false,"spectraStackAlignments":true,"spectraCenterAlignments":true,"realImaginary":false,"peakTool":true,"integralTool":true,"zonePickingTool":false,"slicingTool":false,"autoRangesTool":false,"zeroFillingTool":false,"phaseCorrectionTool":false,"baseLineCorrectionTool":false,"FFTTool":false,"multipleSpectraAnalysisTool":false,"exclusionZonesTool":false}},"controllers":{"dimmedSpectraTransparency":0.1},"formatting":{"nucleus":[{"key":"1H","name":"1H","ppm":"0.00","hz":"0.00"},{"key":"13C","name":"13C","ppm":"0.00","hz":"0.00"},{"key":"15N","name":"15N","ppm":"0.00","hz":"0.00"},{"key":"19F","name":"19F","ppm":"0.00","hz":"0.00"},{"key":"29Si","name":"29Si","ppm":"0.00","hz":"0.00"},{"key":"31P","name":"31P","ppm":"0.00","hz":"0.00"}],"nucleusByKey":{},"panels":{}}},"prediction":{"version":1,"label":"Prediction workspace","display":{"general":{"experimentalFeatures":false},"panels":{"spectraPanel":true,"rangesPanel":true,"zonesPanel":true,"predictionPanel":true,"informationPanel":false,"peaksPanel":false,"integralsPanel":false,"structuresPanel":false,"filtersPanel":false,"summaryPanel":false,"multipleSpectraAnalysisPanel":false,"databasePanel":false}},"controllers":{"dimmedSpectraTransparency":0.1},"formatting":{"nucleus":[{"key":"1H","name":"1H","ppm":"0.00","hz":"0.00"},{"key":"13C","name":"13C","ppm":"0.00","hz":"0.00"},{"key":"15N","name":"15N","ppm":"0.00","hz":"0.00"},{"key":"19F","name":"19F","ppm":"0.00","hz":"0.00"},{"key":"29Si","name":"29Si","ppm":"0.00","hz":"0.00"},{"key":"31P","name":"31P","ppm":"0.00","hz":"0.00"}],"nucleusByKey":{},"panels":{}}}}}
```

**Comment by hamed-musallam** [comment]
@lpatiny 
can you test it one more time

**Comment by lpatiny** [comment]
For sure the version when to 5 but I would expect if we change of version we clear everything and reset to default.

I had some weird preferences (all options but none selected)



This could be due to testing all the versions so not sure if anything should be done.

**Comment by hamed-musallam** [comment]
> For sure the version when to 5 but I would expect if we change of version we clear everything and reset to default.
> 
> I had some weird preferences (all options but none selected)
> 
> 
> 
> This could be due to testing all the versions so not sure if anything should be done.

How I can reproduce this case?

**Pull request merged**
