### PR TITLE
feat: improve general settings

### PR DESCRIPTION
**Pull request by hamed-musallam**

### CODE REVIEW

**Comment by lpatiny** [comment]
LGTM. @hamed-musallam just try to figure out why some tests are not passing.

**Comment by hamed-musallam** [comment]
@lpatiny 

This bug will go once we merge it, but we have to discuss if we need to hide the tool completely from the general setting, do we have any case we need that?

**Comment by lpatiny** [comment]
Most of the workspace have no tools at all

image

This seems strange to me.

**Comment by hamed-musallam** [comment]
@lpatiny 

this is just because the local storage did not update, I have to change the local storage version number and it will be reset with the new changes.

you can remove the data from storage and reload the NMRium

**Comment by hamed-musallam** [comment]
@lpatiny 

can you test the functionality?

**Comment by lpatiny** [comment]
The functionalities work as expected.

I'm trying to figure out what the 'Reset' button is doing

image

Apparently it resets the settings for the current workspace.

I think it should be moved to the top next to the 'workspace' drop down menu and renamed to 'Reset workspace settings'. Clicking on this button should not close the dialog box.

The current `Reset` button should be renamed to `Cancel` and put back the original settings when the dialog was opened.

**Comment by hamed-musallam** [comment]
@lpatiny 

to make the behavior consistent any change happens to be permanent you should click on the save button, in case of reset it is reset the properties visually (temporary in front of the user) and to make it permanent you have to click on the Save button.

**Pull request merged**
