### PR TITLE
Fix modals style and general preferences

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes: https://github.com/cheminfo/nmrium/issues/1771

### CODE REVIEW

**Review by targos — CHANGES_REQUESTED** [review]
The goal of `react-science` is to take care of the style of common components as much as possible. We should do general changes to the style of modals in `react-science` so it benefits other projects and doesn't make nmrium more complex.
Also I think in this case, the styles for the body of the about dialog (color of links, bullet points, size of image, etc) is very specific and should not be applied to other modals.
Can you please open a PR on `react-science` with a subset of the changes that we can review?

**Comment by wadjih-bencheikh18** [comment]
> Can you please open a PR on `react-science` with a subset of the changes that we can review?

Here's the PR that will allow us to change header text position in `react-science` modal 
https://github.com/zakodium-oss/react-science/pull/512

**Comment by targos** [comment]
What is the modal for which you want to change the header position?

**Comment by wadjih-bencheikh18** [comment]
> What is the modal for which you want to change the header position?

I have to change the position of general preferences modal

**Comment by targos** [comment]
I have trouble to understand what this PR does. I see it adds "maxWidth" property, but there is no difference between this PR and https://dev.nmrium.org (main branch), whatever is the size of the browser window.

**Comment by wadjih-bencheikh18** [comment]
> I have trouble to understand what this PR does. I see it adds "maxWidth" property, but there is no difference between this PR and https://dev.nmrium.org (main branch), whatever is the size of the browser window.

I followed what Daniel mentioned here https://github.com/cheminfo/nmrium/issues/1771#issuecomment-1285741723 to check if there any difference. Now i'm trying to change modal content style so it will adapt screen size

**Pull request merged**
