### PR TITLE
refactor: simplify the prediction

### PR DESCRIPTION
**Pull request by hamed-musallam**
- [X] https://github.com/cheminfo/nmrium/issues/2358

### CODE REVIEW

**Comment by lpatiny** [comment]
Replace prediction is great. Could we also add a second button 'Add prediction'^

image

Replace would replace the last added prediction.

Can we have the edition mode even when it is empty ? If I click on the 'prediction' workspace I still need to click to call the editor

image


Could we have a more compact design ? Font could be smaller and also 'Line width' could be next to 'Frequency'

image

Most of the time we will not change those preferences.

Please remove this 'Auto save' message. Not sure why it is there.

image

Is there a simple way to have a local state for the editor and that the displayed molecule as floating is related to the prediction ? Currently we can edit the molecule but the displayed spectrum is possibly not the one corresponding to the molecule

**Comment by hamed-musallam** [comment]
> Add prediction 

is it going to append the new predicted spectra to the existing ones?

>Please remove this 'Auto save' message. Not sure why it is there.

I added the message to notify the user that the change is synced locally, i will remove it.

>Could we have a more compact design ? Font could be smaller and also 'Line width' could be next to 'Frequency'

yes, we can do that and make the form compact.

>Is there a simple way to have a local state for the editor and that the displayed molecule as floating is related to the prediction ? Currently we can edit the molecule but the displayed spectrum is possibly not the one corresponding to the molecule

i did not get what you need me to do. can you clarify things for me in another way

**Comment by hamed-musallam** [comment]
@lpatiny 

`StructureEditor` onChange callback not triggering from the first click once we re-render the editor, you need to trigger twice

**Comment by lpatiny** [comment]
Functionality looks great ! You may merge it when it is ready.

**Pull request merged**
