### PR TITLE
Change the dom to not allow the "Structures" panel to expand

### PR DESCRIPTION
**Pull request by Sebastien-Ahkrin**
Closes: https://github.com/cheminfo/nmrium/issues/1341

@lpatiny Actually i have that (with this fix)
Capture d’écran 2022-02-01 à 16 25 38

Do this works with your example ?

### CODE REVIEW

**Comment by lpatiny** [comment]
Seems to me it is not fixed.

Just draw a long vertical molecule and put a `O` in the bottom.

**Comment by Sebastien-Ahkrin** [comment]
Actually, i can get something like that:
Capture d’écran 2022-02-03 à 11 39 47

:)

**Comment by targos** [comment]
Nice, now the size is correct by default, but there is still an issue when the container becomes smaller (for example if you open other panels).

image

Usually this is fixed by putting `min-height: 0` on the right flex elements.

**Comment by targos** [comment]
See here. You need `min-height: 0` on two more elements and it works: 
image

**Pull request merged**
