### PR TITLE
chore: add hidden way to test thrown errors in production

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
@hamed-musallam Is that ok for you? Sometimes we want to test changes to error reporting and it would be very useful to simulate bugs in nmrium.
This adds a hidden way:
- Open About modal
- Shift+Alt+Click on "Zakodium" to make the hidden options appear

**Comment by hamed-musallam** [comment]
> @hamed-musallam Is that ok for you? Sometimes we want to test changes to error reporting and it would be very useful to simulate bugs in nmrium. This adds a hidden way:
> 
> * Open About modal
> * Shift+Alt+Click on "Zakodium" to make the hidden options appear

I follow your instruction and it seems it does not work https://throw-secret.nmrium.pages.dev/

**Comment by targos** [comment]
https://github.com/cheminfo/nmrium/assets/2352663/f7bb3a6b-0c34-4545-b304-f8368b738638

**Comment by hamed-musallam** [comment]
Sorry, because  i use an external keyboard ( Logi ), it has two keys, option and Alt, now it works for me Thanks

**Pull request merged**
