### PR TITLE
feat: zoom in/out with the mouse wheel

### LINKED ISSUE #2962: Zooming in and out with the mouse wheel
I suggest adding a functionality to zoom in and out of the spectrum in a gradual fashion rather than by selecting a zone. Some commercial software have this functionality and it is very useful when we want to increase or decrease the zoom window. Less annoying than double clicking to a previous zoom window. For example, one could hold the right mouse button and scroll the mouse wheel at the same time.

### PR DESCRIPTION
**Pull request by hamed-musallam**
close #2962

### CODE REVIEW

**Comment by lpatiny** [comment]
Works very well ! Maybe we could open another issue to implement something similar for 2D spectra.

**Comment by lpatiny** [comment]
@targos Do you have an idea why we the action Cloudflare Pages fails since couple of days ? The status can not be reported.

**Comment by targos** [comment]
It seems that Cloudflare changed the name of the check. I updated the requirements to use the new one.

**Comment by lpatiny** [comment]
Great ! Works very well.

**Review by lpatiny — APPROVED** [review]

**Pull request merged**
