### PR TITLE
fix: update dependencies

### PR DESCRIPTION
**Pull request by targos**
re-introduce shadow root with style reset

Closes: https://github.com/cheminfo/nmrium/issues/1424

### CODE REVIEW

**Comment by targos** [comment]
Todo: try to only update analysis-ui-components and not the other dependencies.

**Comment by targos** [comment]
TODO:
- Try to listen to keyboard events on shadow root. (Peak delete issue)
- Try to change the value used when the mouse moves. (Range resize issue)

**Comment by hamed-musallam** [comment]
thank you @targos , i will take a look.

**Comment by hamed-musallam** [comment]
@targos 
can you take a look at why the test  and deploy preview always failed

**Comment by targos** [comment]
@hamed-musallam does `npm run build-no-minify` work without crashing on your computer?

**Comment by hamed-musallam** [comment]
@targos 
yes,  ``` npm run build-no-minify ``` works without crashing

**Comment by hamed-musallam** [comment]
@targos 
 export as SVG not working anymore
image

**Comment by hamed-musallam** [comment]
@targos
i need to do one more thing before we merge, can we delay the merger for tomorrow

**Comment by hamed-musallam** [comment]
@targos 
could you please merge the PR if you did not have any comments, I completed my work on this branch

**Pull request merged**
