### PR TITLE
check symmetry first for manual range picking

### PR DESCRIPTION
**Pull request by jobo322**
the symmetry check will be manage by multiplet-analysis package and we will use signalJoinCouplings to merge couplings, e.g. the pattern `dd` with closer coupling values into `t` based in a `tolerance` option.

### CODE REVIEW

**Comment by lpatiny** [comment]
This looks much better than before. The idea is to check first if the multiplet is symmetric before applying the multiplet analysis right ?

There is a related bug: https://github.com/cheminfo/nmrium/issues/2340 but this can be solved after.

**Comment by lpatiny** [comment]
Could you also check the range picking on a 13C. Because it fails. It never finds out it is a singulet.

**Comment by targos** [comment]
Please take the time to write at least title to your pull requests.

**Comment by jobo322** [comment]
> Please take the time to write at least title to your pull requests.

I agree, I will continue adding a description for each PR.

**Comment by jobo322** [comment]
> This looks much better than before. The idea is to check first if the multiplet is symmetric before applying the multiplet analysis right ?
> 
> There is a related bug: #2340 but this can be solved after.

actually it is done at the moment to merge coupling constants. It is based in a tolerance option.

**Pull request merged**
